import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full border-b p-4">
          <nav className="flex justify-center gap-6">
            <a href="#" className="hover:underline">sobre nosotros</a>
            <a href="#" className="hover:underline">cotizaciones</a>
            <a href="#" className="hover:underline">contactanos</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
